# Generated by Django 3.2.9 on 2022-04-27 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooking_method',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo1',
            field=models.ImageField(default='', max_length=254, upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo2',
            field=models.ImageField(default='', max_length=254, upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='photo3',
            field=models.ImageField(default='', max_length=254, upload_to='photos'),
            preserve_default=False,
        ),
    ]
