# Generated by Django 3.2.9 on 2022-04-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20220427_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo1',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo2',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo3',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='img'),
        ),
    ]
