# Generated by Django 3.2.9 on 2022-04-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220429_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='img'),
        ),
    ]
