# Generated by Django 3.2.9 on 2022-04-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20220429_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo1',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo2',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo3',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='img'),
        ),
    ]
